export const GET_DEFAULT_TICKET = "GET_DEFAULT_TICKET";
export const GET_DEFAULT_TICKET_SUCCESS = "GET_DEFAULT_TICKET_SUCCESS";
export const GET_DEFAULT_TICKET_FAIL = "GET_DEFAULT_TICKET_FAIL";

export const GET_PREVIOUS_PAGE = "GET_PREVIOUS_PAGE";
export const GET_PREVIOUS_PAGE_SUCCESS = "GET_PREVIOUS_PAGE_SUCCESS";
export const GET_PREVIOUS_PAGE_FAIL = "GET_PREVIOUS_PAGE_FAIL";

export const GET_NEXT_PAGE = "GET_NEXT_PAGE";
export const GET_NEXT_PAGE_SUCCESS = "GET_NEXT_PAGE_SUCCESS";
export const GET_NEXT_PAGE_FAIL = "GET_NEXT_PAGE_FAIL";
