// Async
export const GET_DEFAULT_TICKET = "GET_DEFAULT_TICKET";
export const GET_DEFAULT_TICKET_SUCCESS = "GET_DEFAULT_TICKET_SUCCESS";
export const GET_DEFAULT_TICKET_FAIL = "GET_DEFAULT_TICKET_FAIL";

export const LOAD_TICKETS = "LOAD_TICKETS";
export const LOAD_TICKETS_SUCCESS = "LOAD_TICKETS_SUCCESS";
export const LOAD_TICKETS_FAIL = "LOAD_TICKETS_FAIL";

// No side effect
export const GET_PREVIOUS_PAGE = "GET_PREVIOUS_PAGE";

export const GET_NEXT_PAGE = "GET_NEXT_PAGE";
export const GET_NEXT_PAGE_SUCCESS = "GET_NEXT_PAGE_SUCCESS";

export const GET_NEXT_PAGE_TO_QUICK = "GET_NEXT_PAGE_TO_QUICK";

export const REACH_END = "REACH_END";

export const SELECT_SINGLE_TICKET = "SELECT_SINGLE_TICKET";
export const REMOVE_SINGLE_TICKET = "REMOVE_SINGLE_TICKET";
